# Generated by Django 4.2.6 on 2023-10-26 17:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location')),
                ('action', models.CharField(max_length=200, verbose_name='Action')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=120), verbose_name='Duration of action')),
                ('is_public', models.BooleanField(default=True, verbose_name='A sign of a public habit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Related habit',
                'verbose_name_plural': 'Related habits',
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location')),
                ('time', models.TimeField(default='12:00', verbose_name='Action execution time')),
                ('action', models.CharField(max_length=200, verbose_name='Action')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='A sign of a pleasant habit')),
                ('frequency', models.DurationField(default=datetime.timedelta(seconds=28800), verbose_name='Interval')),
                ('reward', models.CharField(blank=True, max_length=200, null=True, verbose_name='Reward')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=120), verbose_name='Duration of action')),
                ('is_public', models.BooleanField(default=False, verbose_name='A sign of a public habit')),
                ('last_execution_time', models.DateTimeField(auto_now=True, verbose_name='Last execution time')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.relatedhabit', verbose_name='Related action')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
            },
        ),
    ]
