# Generated by Django 4.2.6 on 2023-10-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.TimeField(default='00:02:00', verbose_name='Duration of action'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.TimeField(default='04:00:00', verbose_name='Interval'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(default='12:00:00', verbose_name='Action execution time'),
        ),
        migrations.AlterField(
            model_name='relatedhabit',
            name='duration',
            field=models.TimeField(default='00:02:00', verbose_name='Duration of action'),
        ),
    ]
